# Joint limits for RS-A3 robot arm
# Based on motor specifications: RS00 (joints 1-3), RS05 (joints 4-6)

joint_limits:
  L1_joint:
    has_velocity_limits: true
    max_velocity: 33.0  # RS00: 33 rad/s
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: false
    max_jerk: 100.0
    
  L2_joint:
    has_velocity_limits: true
    max_velocity: 33.0  # RS00: 33 rad/s
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: false
    max_jerk: 100.0
    
  L3_joint:
    has_velocity_limits: true
    max_velocity: 33.0  # RS00: 33 rad/s
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: false
    max_jerk: 100.0
    
  L4_joint:
    has_velocity_limits: true
    max_velocity: 50.0  # RS05: 50 rad/s
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: false
    max_jerk: 150.0
    
  L5_joint:
    has_velocity_limits: true
    max_velocity: 50.0  # RS05: 50 rad/s
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: false
    max_jerk: 150.0
    
  L6_joint:
    has_velocity_limits: true
    max_velocity: 50.0  # RS05: 50 rad/s
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: false
    max_jerk: 150.0

